# Generated by Django 5.2.3 on 2025-06-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageant', '0002_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='gallery_photos/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
